####################
# Global Repo Settings: https://github.com/probot/settings#usage
# Global Wex Settings: https://github.com/wexinc/global-settings
####################

repository:
  name: codeflix
  description: Netflix clone
  homepage:
  topics: github, netflix, microservices, typescript, clean architecture, domain driven design
  private: false
  has_issues: true
  has_projects: false
  has_wiki: true
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

labels:
  - { color: '80C000', name: 'compliance',   description: 'Change for compliance, standards or governance' } # Blueish
  - { color: '80C000', name: 'feature',   description: '' } # Green
  - { color: 'FF8000', name: 'refactor',  description: '' } # Orange
  - { color: 'C00000', name: 'bug',       description: '' } # Red
  - { color: '00C0FF', name: 'ci',        description: 'Item related to continuous integration' } # Light Blue
  - { color: '4080FF', name: 'cd',        description: 'Item related to continuous delivery' } # Blue
  - { color: 'C080FF', name: 'docs',      description: '' } # Light Purple
  - { color: '000000', name: 'question',  description: '' } # Black
  - { color: 'C00000', name: 'blocked',   description: '' } # Red
  - { color: 'DDDDDD', name: 'duplicate', description: '' } # Gray
  - { color: 'DDDDDD', name: 'invalid',   description: '' } # Gray
  - { color: 'DDDDDD', name: 'released',  description: '' } # Gray

# See https://docs.github.com/en/rest/reference/teams#add-or-update-team-repository-permissions for available options
# teams:
#   - name: 'technology'
#     permission: push

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: [ ]
          teams: [ ]
      required_status_checks:
        strict: true
        contexts: [ ]
      enforce_admins: false
      required_linear_history: true
      restrictions:
        apps: [ ]
        users: [ ]
        teams: [ ]
