version: '3'

services:
  app:
    build: .
    container_name: micro-videos-python-app
    volumes:
      - .:/home/python/app
    
  db:
    image: postgres:14.3-alpine
    container_name: postgres
    tty: true
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - .docker/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"